### ISSUE TITLE
Make map dimentions dependant on device

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#109]
A user with a tablet shoudn't get a 300x300 map (which it is currently)

**Comment by jtran19** [comment]
Here ya go!

http://stackoverflow.com/questions/1016896/how-to-get-screen-dimensions

I think we may have to use the 2nd method because the map is prepared before the activity is finished loading, so we _technically_ don't have an Activity yet.

**Comment by jtran19** [comment]
Implemented with DisplayMetrics
