### ISSUE TITLE
Tapping on "Find Me" when there's already an origin will cause it to revalidate even when it doesn't need to.

### ISSUE THREAD

**Issue by jtran19** [grokpot/Routy#122]

**Comment by grokpot** [comment]
Don't know if this needs to change. What if they have a saved origin in
preferences, drive somewhere, and then need to revalidate their position?

IMO If they want to waste the time revalidating, let them.

**Comment by jtran19** [comment]
Yea I'm thinking about it right now.  Seems to be fast enough if there's already a valid origin.  May not be an issue after all.

**Comment by jtran19** [comment]
Not fixing for now.  Will reopen if it actually becomes a use case issue.
