### ISSUE TITLE
Enable 'Go back and choose a new origin' button in Destinations Activity. Manipulate data accordingly..

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#13]

**Comment by grokpot** [comment]
Example Case:

A user enters an origin and proceeds to DestinationActivity.
A user enters 5 destinations.

Now there's two options:
A user presses the back key
A user presses "go back and choose a new origin"
- How do these differ?
- Should we save the destinations they've already entered?

**Comment by ericthompson** [comment]
1.) These should not differ in my opinion.
2.) I believe we should save the destinations. We can just save the strings corresponding to the text actually in the text box - this may mean they will be re-validated, but that would be OK and might make the transitions between screens easier. It's very easy to remove destinations so if you don't like what's there - not hard to fix. It's much more annoying and time consuming to re-add something. The tradeoff between saving and not saving for the user is very noticeable.

Opinions?

**Comment by jtran19** [comment]
1. I'm an iOS user, so I'd like to defer to Ryan on whether it's intuitive for an Android user to hit the back button if they would want to edit their origin.  Your thoughts on that?
2. I agree that we should saved the destinations that they've entered.  Just because they change their mind on the origin, doesn't mean they changed their mind on the destinations.

**Comment by grokpot** [comment]
Yeah I don't see a point in "go back and choose your origin". To me, it's
intuitive to click back.

I suppose we should overwrite the onFinish() method to check for
destinations and save them in DestinationActivity's shared prefs.

onCreate() should then load the destinations from shared prefs. This means
that if I run errands on Monday and then use the app again on Friday, those
destinations would still be there. Thoughts on that? IMO I would be
impressed and I'm an advocate.

-R

**Comment by jtran19** [comment]
Yes, we need to address the onPause(), onDestroy(), onFinish(), etc. methods and what needs to be done in each case.  Right now we do nothing...anything that's saved is saved in global Java variables and can disappear whenever depending on the Android subsystem.

**Comment by grokpot** [comment]
From what I've read, we don't need to touch onDestroy() - that's more of an Android garbage collection thing that's handled by the system. Need verification on this however.

onPause() I suppose will also store the destinations. Example: A user enters 5 destinations, presses the home key, for some reason our app gets GC'd, and then they open it up again. Those destinations should be there.

onFinish() is the method called when the app exits. This is what is called when the user presses back and goes to OriginActivity. We definitely need to store shared prefs here.
