### ISSUE TITLE
Loading spinners

### ISSUE THREAD

**Issue by jtran19** [grokpot/Routy#17]
Some sort of indication that the app is doing something.

Use LoadingDialog.  It may need some more work though.

**Comment by jtran19** [comment]
Need to disable tapping on anything while it's loading. Might need to consider the case where it takes "too long" for whatever is loading.

**Comment by jtran19** [comment]
I had an idea to do an "inline" loading spinner (circular) on the row that's being validated.  Or we can do a popup loading spinner that shows in a dialog for everything.

Thoughts?

**Comment by grokpot** [comment]
Where are we at on this? Loading spinner for OA looks good. 
- Loading spinner for places validation in DA?
- Loading spinner for progressing from DA to RA?

**Comment by jtran19** [comment]
Working on that today. Loading dialog is in working, just needs to be added into the existing AsyncTasks. Will look just like the OA spinner.

**Comment by jtran19** [comment]
Donzo!
