### ISSUE TITLE
Add "Start Over" button

### ISSUE THREAD

**Issue by jtran19** [grokpot/Routy#24]
Put a button on the Results screen that starts the entire process over (select origin, select destination, calculate route).

**Comment by grokpot** [comment]
Thoughts on this? If we're not going to include a 'Change origin' button, I say we stick with the general Android feel and make the user use the back button (at max two 'back' presses)

**Comment by jtran19** [comment]
I think I'm ok with back x2.

**Comment by ericthompson** [comment]
If its standard, I'm down.
