### ISSUE TITLE
Add "swipe-to-remove" functionality to destinations list

### ISSUE THREAD

**Issue by jtran19** [grokpot/Routy#28]
Basic swipe-to-remove is working, but there's no visual feedback...it just disappears.

**Comment by ericthompson** [comment]
Is this worth pursuing? Something about this strikes me as a little unnecessary. Especially now that we've gone ahead and included the icons. I'd much rather see swiping to move between screens.

**Comment by jtran19** [comment]
Agree with Eric.

On Nov 20, 2012, at 12:34 PM, ericthompson notifications@github.com wrote:

Is this worth pursuing? Something about this strikes me as a little
unnecessary. Especially now that we've gone ahead and included the icons.
I'd much rather see swiping to move between screens.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ryanprater/Routy/issues/28#issuecomment-10566825.

**Comment by ericthompson** [comment]
Punting this one....

**Comment by jtran19** [comment]
Add to market release?

On Nov 28, 2012, at 2:17 PM, ericthompson notifications@github.com wrote:

Punting this one....

—
Reply to this email directly or view it on
GitHubhttps://github.com/ryanprater/Routy/issues/28#issuecomment-10819480.
