### ISSUE TITLE
Convert total route distance to miles and display in better fashion

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#29]

**Comment by ericthompson** [comment]
Do we want to do the whole duration/distance switch? Either way, at least getting this into miles is pretty important.

**Comment by jtran19** [comment]
Yes.  And I think even a Miles/KM preference would be nice.

**Comment by ericthompson** [comment]
I mean right now it's in km... This is 'murica. And in 'murica we don't use no stinkin' metric system.

**Comment by grokpot** [comment]
Closed in recent commit. No Mi/Km switch, creating a new ticket for that.
