### ISSUE TITLE
Remove blank destinations from UI when user presses "Route it!"

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#31]

**Comment by jtran19** [comment]
Do you mean remove the rows that have blank EditText fields?

Should we not allow them to add a new one if the last one in the list has no text in it?

Also, the back-end of the destinations screen is ignoring any blank rows already, so you don't have to do that in addition to removing the views.

**Comment by grokpot** [comment]
1. Yes
2. At first I thought "No", but that means a user has to press "add", enter text, press "add" again, and so on. If they know they have 5 errands to run, I say let them press "add" 5 times and then enter text.
3. Sweet, perfect. This clarifies a lot and relates to point 1. If a user has 5 empty destinations and presses "route it", they shouldn't see 5 empty destinations when they click back. That's a simple UI fix.

**Comment by jtran19** [comment]
Actually, I think #3 is taken care of. I'll try it out. The latest code for that is in the issue6v2 branch.

**Comment by jtran19** [comment]
New "+" and "-" buttons on the destinations rows fixes this issue.
