### ISSUE TITLE
Improve DestinationActivity UI

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#33]
- Style "starting from" text
- Replace 'Remove' buttons with red 'x' image
- Style buttons at bottom of screen

**Comment by jtran19** [comment]
Hold off on this one.  I made some changes to it while doing the Google Places stuff.  I'll post a comment when it's ready to go.

**Comment by jtran19** [comment]
I'm only fixing behavior at this point, so you should be able to make any layout improvements you want to.

**Comment by ericthompson** [comment]
I was thinking we get rid of both the return to origin button and the test button - we can leave the test button in until the last possible moment though. Thoughts?

**Comment by jtran19** [comment]
I agree.

I'm about to start my work on DestinationActivity here in a bit.  I can knock off the "Return to Origin" button while I'm in there.

**Comment by ericthompson** [comment]
I'll leave you to it for the time being. I'm planning on putting the "Route it!" button as the text alone, and killing off the appearance of a button altogether. Take a look at the origin screen to see what I'm talking about.

**Comment by jtran19** [comment]
Now that we've got a lot of "sketchy-ness" in the UI of the app...the default font isn't looking so hot.  Maybe we can make the font smaller?  Just looks really juxtaposed next to the sketchy stuff because it's so straight cut.

Fixed:
- "+" and "-" button behavior
- loading of saved destinations behavior
- remove "return to origin" button -- user will tap "back" to do this

Remaining:
- style "Route It" button

**Comment by ericthompson** [comment]
I can do the Route It thing tonight. Do we want to look through different font families? If someone has an idea, definitely throw it up here.

**Comment by ericthompson** [comment]
It could also be worth looking into one font that seems to work, but also including multiple styles (use bold. italics to spice it up a little). Never underestimate the power of some variety to make stuff look more interesting.

**Comment by grokpot** [comment]
Most of the original issues here have been fixed, but I don't want to create a new issue. As of 11/25/12, here's what needs to happen IMO:
- Fill space between destinations and "route it" button
- "Route it" button needs a line around it, making it look pressable
- I feel the need to put something up top
- _Move the + below the last destination_  <-- Moved to it's own issue

**Comment by jtran19** [comment]
- Just need to add some helpful captions
- Change out the "+" button

**Comment by jtran19** [comment]
Eric, did you implement the new hint text for the destination row EditText components?  If so, I think we can close this unless someone sees additional improvements we need.

**Comment by ericthompson** [comment]
Yeah, I changed the strings in the resource file directly. Are we
officially happy with them?

**Comment by grokpot** [comment]
The activity LGTM for a Beta release. It could use some work before the market release.
