### ISSUE TITLE
Switching from black to white?

### ISSUE THREAD

**Issue by ericthompson** [grokpot/Routy#38]
I thought once you went black you never went back...

But in all seriousness, take a look at the current styling on the destination screen and on the splash screen for an idea about what white text/logos would look like. Compare against the origin screen for how black stuff looks. Which one do we want to go with?

**Comment by jtran19** [comment]
Did you push code just now?

**Comment by ericthompson** [comment]
You were referring to the logos and shit. Yes, it's been up since early this morning too. Did it not make it?

**Comment by ericthompson** [comment]
Has everyone had a chance to look at the graphic styling? If you guys want me to switch it to white, I can do it.

**Comment by jtran19** [comment]
I vote for white.  I'd like to find out about including our own custom font for the actual TextView and EditText components.

**Comment by ericthompson** [comment]
K - I'll change the origin screen to reflect it. Once I get those two logos at the bottom and the main text under the main logo to white, everyone should take a look and see if we like the whole app's styling. I'm leaning towards the white myself.
