### ISSUE TITLE
Infinite Loop in checkforInternetConnectivity in MainActivity

### ISSUE THREAD

**Issue by ericthompson** [grokpot/Routy#41]
Kept getting stuck in an infinite loop last night when I was trying to add in sounds. It would just keep popping the error message up. This, in conjunction with my error noise (this really pathetic sounding robot moan) made me laugh hysterically. I was also drunk. That helped.

Thinking back on this, I think this is somewhat close to the behavior that Jeff and I discussed. In practice though, I think I would've definitely preferred if the app just shut down so that I can handle the issue. Continuously bringing up that dialog box over and over again definitely didn't convey the right message. Do we like the idea of the app shutting down?

**Comment by jtran19** [comment]
Doesn't the button on the error message say "Try Again"?  I think I like the idea of having a "Try Again" and "Quit" button.  That way the user has control <i>and</i> they know what is going to happen.  Thoughts on this approach?

**Comment by grokpot** [comment]
Can you give us some steps to reproduce the error?

**Comment by jtran19** [comment]
- Add "Quit" button next to "Try Again"
- Don't let the user cancel (or back out of) the dialog

**Comment by ericthompson** [comment]
Turn off the wifi/network, force stop Routy (if it was running before), and try to load Routy. It brings up an error dialog and then only gives you the ability to "Try Again." We should add a quit and not allow the user to press outside of the error dialog and get stuck permanently in the splash screen.
