### ISSUE TITLE
Route it! with no destinations crash

### ISSUE THREAD

**Issue by ericthompson** [grokpot/Routy#42]
When you select an origin, go to the destinations screen, and leave it empty, if you try to click Route it! it just crashes and dies. It cites line 38 of the CalculateRouteTask.java file as the source of the problem. It acts like there was an exception and when it tries to e.getMessage() there is no message - it's like it's null. Very strange, might want to take a look into it.

**Comment by jtran19** [comment]
I'm on it. I'll check it out tomorrow. Planning on throwing a lot of time
at Routy tomorrow.

I think it may be similar to the 1-destination problem we had before.
