### ISSUE TITLE
Integrate with Google Places API so that Routy can understand place names in addition to addresses.

### ISSUE THREAD

**Issue by jtran19** [grokpot/Routy#6]
"HEB" will return the closest HEB, instead of being interpreted as an invalid address.

**Comment by grokpot** [comment]
Nice. Explain how that works?

**Comment by jtran19** [comment]
So right now if you enter "University of Texas" into Routy anywhere it asks for an "address", it assumes that what you give it is a street address.  We can potentially use the Google Places API to say: "I want to find <place name> near <user's lat/long location>" like you would type into Google Maps online.

If we can get this to work, the use case would be:
1. User enters a place name (eg. "HEB") into one of the destination fields.
2. Google Places API will find the closest "HEB" to the origin the user entered/accepted on the previous screen.
3. We grab the actual address from what Google Places returned and use it as that particular destination.

It's definitely an enhancement, but if we've got time before the Beta release it would make the app a lot more user friendly.  Since most of the time you don't know the exact address for that HEB you want to go to, and sometimes you don't care which HEB you end up going to anyway.

Jeff

**Comment by grokpot** [comment]
Damn I like that feature a lot.

Maybe allow for users to choose which HEB as well? That's a feature-feature.

Also - It looks like you can respond to an issue via email and GitHub posts your comment here.

**Comment by jtran19** [comment]
I think we might have to do a "pick from this list of 3-5" kind of thing for this one.  When I call the Google Places API with "name=heb" as the criteria, it returns the TXU Energy blahblahblah "inside Fiesta" on I-35 as the FIRST result (the rest are actual HEB locations).

This seems to be an issue with the Places API...not how we're handling things.
