### ISSUE TITLE
Make map fragment have rounded corners

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#65]
Because it looks nice!
http://blog.blundell-apps.com/rounded-corners-mapview/

**Comment by jtran19** [comment]
Is there a way to style this?

**Comment by grokpot** [comment]
http://stackoverflow.com/questions/14469208/is-there-a-way-to-implement-rounded-corners-to-a-mapfragment

**Comment by jtran19** [comment]
What about rounded corners on the entire app itself? Seen it a few times and it's subtle but makes the app really stand out from others.

**Comment by grokpot** [comment]
Jeff did you move this back to Market Release milestone or did I forget to move it?

Gotta punt on this one, looked into it and it gets pretty funky difficult. You or E can take a look if you wanna tackle it. Moving it to Patch 1

**Comment by jtran19** [comment]
Let's punt it completely.  I don't think it'll add enough value considering it sounds like a tough one to tackle.  We have enough stuff to work on.
