### ISSUE TITLE
Allow user to zoom/pan mapview

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#66]
http://stackoverflow.com/questions/11486501/how-do-i-get-mapview-setbuiltinzoomcontrolstrue-to-work
http://stackoverflow.com/questions/6546108/mapview-inside-a-scrollview

**Comment by jtran19** [comment]
Ryan, think we can have this and #65 done for GDC?

**Comment by jtran19** [comment]
Update to new MapFragment fixes this.
