### ISSUE TITLE
Solve dialog/mapview conflict in RA

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#69]
ResultsActivity can either extend FragmentActivity or MapViewActivity, and the contexts conflict for dialogs and mapviews.

**Comment by jtran19** [comment]
I think you can take FragmentActivity out of it because MapActivity
extends FragmentActivity at some point. Try it and see.

**Comment by grokpot** [comment]
http://stackoverflow.com/questions/7918434/is-it-possible-to-use-mapview-with-fragmentmanager-and-listfragment

**Comment by grokpot** [comment]
We might have reached an end on this one...

Seems to be a problem that can currently only be fixed with a 3rd party repo. Not something I'm wanting to do because we'll then be reliant on outdated code.  Also read another SO post saying that then _every_ Activity that extends FragmentActivity also extends MapViewActivity.

http://stackoverflow.com/questions/11829782/fragmentactivity-with-a-fragment-containing-a-mapview

**Comment by jtran19** [comment]
Scratch my last suggestion. Just manually build/show the needed dialogs inside ResultsActivity.
