### ISSUE TITLE
Cursor should be at end of hint text for origin Edit Text on originActivity

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#83]
Right now with the text centered, the cursor is placed in the middle of the hint text. boo.

**Comment by jtran19** [comment]
How is the hint text being placed in the text field?  If you do it via the XML, it should handle disappearing/appearing automatically.

**Comment by grokpot** [comment]
The text is now centered in the EditText.

When a user clicks on an edit text field, the hint text doesn't disappear
until the user enters a character

So before the first character entry, the EditText has focus with cursor
centered in the middle of the hint text
