### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#89]
Simple, Simple, Simple.

Here's some more button ideas: https://github.com/ququplay/jquery-mobile-flat-ui-theme

**Comment by jtran19** [comment]
Nice find. I like that.

On Apr 5, 2013, at 9:30 AM, Ryan Prater notifications@github.com wrote:

Simple, Simple, Simple.

Here's some more button ideas:
https://github.com/ququplay/jquery-mobile-flat-ui-theme

—
Reply to this email directly or view it on
GitHubhttps://github.com/ryanprater/Routy/issues/89
.

**Comment by grokpot** [comment]
Closing for now. Can re-open if we decide to do anything else big.
