### ISSUE TITLE
FQ if user enters invalid origin and destination, then exits

### ISSUE THREAD

**Issue by grokpot** [grokpot/Routy#92]
App crashes from null value being read instead of string.

04-06 14:20:32.916: E/AndroidRuntime(23576): FATAL EXCEPTION: main
04-06 14:20:32.916: E/AndroidRuntime(23576): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.routy/org.routy.OriginActivity}: java.lang.IllegalStateException: Expected a string but was NULL
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2049)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2083)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.app.ActivityThread.access$600(ActivityThread.java:134)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.os.Handler.dispatchMessage(Handler.java:99)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.os.Looper.loop(Looper.java:137)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.app.ActivityThread.main(ActivityThread.java:4722)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at java.lang.reflect.Method.invokeNative(Native Method)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at java.lang.reflect.Method.invoke(Method.java:511)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at dalvik.system.NativeStart.main(Native Method)
04-06 14:20:32.916: E/AndroidRuntime(23576): Caused by: java.lang.IllegalStateException: Expected a string but was NULL
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.util.JsonReader.nextString(JsonReader.java:408)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at org.routy.Util.readAddress(Util.java:196)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at org.routy.Util.jsonToAddressList(Util.java:156)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at org.routy.OriginActivity.restoreSavedDestinations(OriginActivity.java:220)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at org.routy.OriginActivity.onCreate(OriginActivity.java:143)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.app.Activity.performCreate(Activity.java:4539)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
04-06 14:20:32.916: E/AndroidRuntime(23576):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2013)
04-06 14:20:32.916: E/AndroidRuntime(23576):    ... 11 more

**Comment by jtran19** [comment]
Without seeing all of the stack trace, my gut tells me that this is due to Routy trying to store null value from the empty text box when the user is exiting the app.

I'll take this one.

**Comment by jtran19** [comment]
What were your exact steps? I can't reproduce this.
